server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:\C:\Users\rkdtn\git-local-repo
#        git:
#          uri: file:\C:\Users\rkdtn\git-local-repo
#          uri: https://github.com/ksc036/spring-cloud-config
#          uri: https://github.com/ksc036/spring-cloud-config
